# Generated by Django 6.0.5 on 2026-05-18 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animalscan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='animalscan',
            index=models.Index(fields=['status'], name='animal_scan_status_43952b_idx'),
        ),
        migrations.AddIndex(
            model_name='animalscan',
            index=models.Index(fields=['-created_at'], name='animal_scan_created_709c59_idx'),
        ),
    ]
