# Generated by Django 6.0.5 on 2026-05-18 09:17

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_initial'),
    ]

    operations = [
        VectorExtension(),
    ]
