# Generated by Django 6.0.5 on 2026-05-18 09:22

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_enable_vector_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Fluff', max_length=100)),
                ('is_shadow', models.BooleanField(default=True)),
                ('face_encoding', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True)),
                ('memory_summary', models.TextField(blank=True, help_text='Rolling summary of past thoughts.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pet_profiles',
            },
        ),
        migrations.AddField(
            model_name='animalscan',
            name='pet_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='scanner.petprofile'),
        ),
        migrations.AddIndex(
            model_name='petprofile',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['face_encoding'], m=16, name='face_vector_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
