# Generated by Django 6.0.5 on 2026-05-18 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_petprofile_animalscan_pet_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPersonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Ворчливый дед, Наивный щенок', max_length=100, unique=True)),
                ('system_prompt', models.TextField(help_text='Главная инструкция для ИИ. Опишите, как питомец должен думать и говорить.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'AI Personalities',
                'db_table': 'ai_personalities',
            },
        ),
        migrations.AddField(
            model_name='petprofile',
            name='personality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.aipersonality'),
        ),
    ]
