# Generated by Django 6.0.5 on 2026-05-20 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_aipersonality_petprofile_personality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MindreaderLoreNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlock_level', models.IntegerField(help_text='Уровень, начиная с которого этот лор может активироваться')),
                ('lore_trigger_weight', models.IntegerField(default=50, help_text='Вероятность выпадения этой ноды при сканировании человека/предмета (от 1 до 100)')),
                ('system_instruction_addon', models.TextField(help_text="Дополнение к системному промпту. Раскрывает характер или кусок истории. Наример: 'Вспомни, как в 1947 году тебя впервые заперли в криокамере. Иронизируй над этим.'")),
                ('story_clue_text', models.TextField(blank=True, help_text='Прямая сюжетная улика/секретный файл, который подмешается в JSON ответ для юзера, если ИИ решит раскрыть тайну.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'mindreader_lore_nodes',
                'ordering': ['unlock_level'],
            },
        ),
        migrations.CreateModel(
            name='ScannerLevelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(db_index=True, help_text='Номер уровня прибора', unique=True)),
                ('scans_required', models.IntegerField(help_text='Суммарное количество сканов, необходимое для ДОСТИЖЕНИЯ этого уровня')),
                ('max_hold_seconds', models.IntegerField(default=3, help_text='Сколько секунд можно удерживать затвор на этом уровне')),
            ],
            options={
                'verbose_name': 'Scanner Level Config',
                'verbose_name_plural': 'Scanner Level Configs',
                'db_table': 'scanner_level_config',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='UserScannerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, help_text='Уникальный UUID девайса для неавторизованных', max_length=255, unique=True)),
                ('total_successful_scans', models.IntegerField(default=0, help_text='Общее количество выполненных сканирований')),
                ('current_level', models.IntegerField(db_index=True, default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scanner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_scanner_profiles',
            },
        ),
    ]
