# Generated by Django 6.0.5 on 2026-05-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_mindreaderlorenode_scannerlevelconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalscan',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, help_text='UUID девайса, выполнившего скан', max_length=255, null=True),
        ),
    ]
