# Generated by Django 6.0.5 on 2026-05-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_animalscan_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerlevelconfig',
            name='extra_time_seconds',
            field=models.IntegerField(default=5, help_text='Сколько секунд видео дописывается после отпускания кнопки на этом уровне'),
        ),
    ]
