# Generated by Django 6.0.5 on 2026-05-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_scannerlevelconfig_extra_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
