# Generated by Django 6.0.5 on 2026-05-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_petprofile_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalscan',
            name='session_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
